source 'http://rubygems.org'

gem 'appium_capybara', '~> 1.2', '>= 1.2.1'
gem 'appium_lib', '~> 8.0'
gem 'capybara'
gem 'cucumber'
gem 'poltergeist'
gem 'pry'
gem 'res'
gem 'rspec-expectations'
gem 'selenium-webdriver'
gem 'site_prism'
